PREFIX ex: <http://example.org/>

SELECT ?person ?person2 ?food ?drink ?cup ?nick
WHERE {
    GRAPH <file://resources/ttl/coffee/coffee.ttl#rdf> {
        {
            ?person ex:eats ?food .
            OPTIONAL { ?person ex:cup ?cup . }
            OPTIONAL { ?person ex:nickname ?nick . }
        }
        {
            ?person2 ex:drinks ?drink .
            OPTIONAL { ?person2 ex:cup ?cup . }
            OPTIONAL { ?person2 ex:nickname ?nick . }
        }
    }
}
