PREFIX ex: <http://example.org/>

SELECT ?a ?b ?c
WHERE {
    GRAPH <file://resources/ttl/coffee.ttl#rdf> {
        ?a ex:rel ?b.
        ?b ex:rel ?c.
        ?c ex:rel ?a.
        FILTER(?a != ?b && ?b != ?c && ?c != ?a && ?a < ?b && ?a < ?c && ?b < ?c)
    }
}