PREFIX ex: <http://example.org/>

SELECT ?who ?what ?age
{
    GRAPH <file://resources/ttl/coffee/coffee.ttl#rdf> {
        ?who ex:eats ex:sushi .
        OPTIONAL {
            { ?who ex:drinks ?what }
            UNION
            { ?who ex:age ?age }
        }
    }
}
ORDER BY ?what