#ifndef GENGODB_COMPILER_DIALECT_GRAPHSUBOP_GRAPHSUBOPSATTRIBUTES_H
#define GENGODB_COMPILER_DIALECT_GRAPHSUBOP_GRAPHSUBOPSATTRIBUTES_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

#define GET_ATTRDEF_CLASSES
#include "gengodb/compiler/Dialect/GraphSubOp/GraphSubOpsAttributes.h.inc"

#endif // GENGODB_COMPILER_DIALECT_GRAPHSUBOP_GRAPHSUBOPSATTRIBUTES_H