/* --====-- (!) This file was generated by Claude Code (!) --====-- */
#ifndef GENGODB_COMPILER_FRONTEND_SPARQLMLIPTRANSLATOR_H
#define GENGODB_COMPILER_FRONTEND_SPARQLMLIPTRANSLATOR_H

#include "lingodb/compiler/Dialect/DB/IR/DBDialect.h"
#include "lingodb/compiler/Dialect/DB/IR/DBOps.h"
#include "lingodb/compiler/Dialect/RelAlg/IR/RelAlgDialect.h"
#include "lingodb/compiler/Dialect/RelAlg/IR/RelAlgOps.h"
#include "lingodb/compiler/Dialect/SubOperator/MemberManager.h"
#include "lingodb/compiler/Dialect/SubOperator/SubOperatorDialect.h"
#include "lingodb/compiler/Dialect/SubOperator/SubOperatorOps.h"
#include "lingodb/compiler/Dialect/TupleStream/TupleStreamDialect.h"
#include "lingodb/compiler/Dialect/TupleStream/TupleStreamOps.h"
#include "lingodb/compiler/Dialect/util/UtilDialect.h"
#include "gengodb/compiler/Dialect/GPM/IR/GPMDialect.h"
#include "gengodb/compiler/Dialect/GPM/IR/GPMOps.h"
#include "gengodb/compiler/Dialect/GPM/IR/GPMOpsAttributes.h"
#include "gengodb/compiler/Dialect/GPM/IR/GPMOpsTypes.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Builders.h"

#include "llvm/Support/raw_ostream.h"

#include <algorithm>
#include <cctype>
#include <map>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

// ============================================================
// AST
// ============================================================
namespace sparql {

struct Term {
   enum class Kind { Iri, Variable, BlankNode };
   Kind kind;
   std::string value;
};

struct Triple {
   Term s, p, o;
};

// Base class for WHERE clause elements.
// Future ARQ operators (FILTER, UNION, …) add new subclasses here.
struct PatternElement {
   enum class Kind { Graph, Optional };
   virtual ~PatternElement() = default;
   virtual Kind kind() const = 0;
};

struct GraphPattern : PatternElement {
   std::string graphUri;
   std::vector<Triple> triples;
   Kind kind() const override { return Kind::Graph; }
};

// SPARQL OPTIONAL { ... } — a nested group joined onto the enclosing group via
// a left outer join, so variables first bound inside may end up unbound (null).
struct OptionalPattern : PatternElement {
   std::vector<std::unique_ptr<PatternElement>> patterns;
   Kind kind() const override { return Kind::Optional; }
};

struct Query {
   std::map<std::string, std::string> prefixes; // label → expansion IRI (""=default)
   bool selectStar{false};
   std::vector<std::string> selectVars;
   std::vector<std::unique_ptr<PatternElement>> patterns;
};

} // namespace sparql

// ============================================================
// Tokenizer
// ============================================================
enum class TK {
   Eof, IRI, PrefixedName, Variable, BlankNode,
   Keyword, LBrace, RBrace, Dot, Comma, Semicolon,
   Star, LeftParen, RightParen, StringLit, Colon, Unknown
};

struct Token { TK kind; std::string value; size_t line{1}; };

class Tokenizer {
   std::string src;
   size_t pos{0};
   size_t line{1};

   char cur() const { return pos < src.size() ? src[pos] : '\0'; }
   char la()  const { return pos + 1 < src.size() ? src[pos + 1] : '\0'; }
   char adv() { char c = src[pos++]; if (c == '\n') line++; return c; }

   void skipWS() {
      while (pos < src.size()) {
         if (std::isspace(static_cast<unsigned char>(cur()))) adv();
         else if (cur() == '#') { while (pos < src.size() && cur() != '\n') adv(); }
         else break;
      }
   }

   std::string readUntil(char end) {
      std::string r;
      while (pos < src.size() && cur() != end) r += adv();
      if (cur() == end) adv();
      return r;
   }

   std::string readStr(char d) {
      std::string r;
      while (pos < src.size() && cur() != d) {
         if (cur() == '\\') { adv(); r += adv(); } else r += adv();
      }
      if (cur() == d) adv();
      return r;
   }

   // Read an alpha-numeric identifier. If immediately followed by ':', treat as
   // prefixed name (PNAME). Otherwise uppercase and return as keyword.
   Token readIdent() {
      std::string name;
      while (pos < src.size() && (std::isalnum(static_cast<unsigned char>(cur())) || cur() == '_' || cur() == '-'))
         name += adv();

      if (cur() == ':' && la() != ':') {
         adv(); // consume ':'
         std::string local;
         while (pos < src.size()) {
            char c = cur();
            if (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '-' || c == '.' || c == '/' || c == '#' || c == '@')
               local += adv();
            else break;
         }
         while (!local.empty() && local.back() == '.') local.pop_back();
         return {TK::PrefixedName, name + ":" + local, line};
      }
      std::string upper = name;
      std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
      return {TK::Keyword, upper, line};
   }

   public:
   explicit Tokenizer(std::string s) : src(std::move(s)) {}

   Token next() {
      skipWS();
      if (pos >= src.size()) return {TK::Eof, {}, line};
      char c = cur();
      if (c == '<')  { adv(); return {TK::IRI, readUntil('>'), line}; }
      if (c == '"')  { adv(); return {TK::StringLit, readStr('"'), line}; }
      if (c == '\'') { adv(); return {TK::StringLit, readStr('\''), line}; }
      if (c == '?' || c == '$') {
         adv();
         std::string n;
         while (pos < src.size() && (std::isalnum(static_cast<unsigned char>(cur())) || cur() == '_')) n += adv();
         return {TK::Variable, n, line};
      }
      if (c == '_' && la() == ':') {
         adv(); adv();
         std::string n;
         while (pos < src.size() && (std::isalnum(static_cast<unsigned char>(cur())) || cur() == '_' || cur() == '-')) n += adv();
         return {TK::BlankNode, n, line};
      }
      if (c == ':') { adv(); return {TK::Colon, ":", line}; }
      if (c == '{') { adv(); return {TK::LBrace,    "{", line}; }
      if (c == '}') { adv(); return {TK::RBrace,    "}", line}; }
      if (c == '.') { adv(); return {TK::Dot,       ".", line}; }
      if (c == ',') { adv(); return {TK::Comma,     ",", line}; }
      if (c == ';') { adv(); return {TK::Semicolon, ";", line}; }
      if (c == '*') { adv(); return {TK::Star,      "*", line}; }
      if (c == '(') { adv(); return {TK::LeftParen, "(", line}; }
      if (c == ')') { adv(); return {TK::RightParen,")", line}; }
      if (std::isalpha(static_cast<unsigned char>(c)) || c == '_') return readIdent();
      adv(); return {TK::Unknown, std::string(1, c), line};
   }
};

// ============================================================
// Parser
// ============================================================
class Parser {
   Tokenizer tz;
   Token tok;

   void advance() { tok = tz.next(); }
   bool is(TK k) const { return tok.kind == k; }
   bool kw(const char* w) const { return tok.kind == TK::Keyword && tok.value == w; }

   Token eat(TK k) {
      if (tok.kind != k)
         throw std::runtime_error("Parse error at line " + std::to_string(tok.line) + ": unexpected '" + tok.value + "'");
      Token t = tok; advance(); return t;
   }
   void eatKw(const char* w) {
      if (!kw(w))
         throw std::runtime_error("Expected '" + std::string(w) + "' at line " + std::to_string(tok.line) + ", got '" + tok.value + "'");
      advance();
   }

   std::string expandPrefix(const std::string& raw, const std::map<std::string, std::string>& pref) {
      auto col = raw.find(':');
      if (col == std::string::npos) return raw;
      auto it = pref.find(raw.substr(0, col));
      return (it != pref.end()) ? it->second + raw.substr(col + 1) : raw;
   }

   sparql::Term parseTerm(const std::map<std::string, std::string>& pref) {
      if (is(TK::IRI))          { std::string v = tok.value; advance(); return {sparql::Term::Kind::Iri, v}; }
      if (is(TK::PrefixedName)) { std::string v = expandPrefix(tok.value, pref); advance(); return {sparql::Term::Kind::Iri, v}; }
      if (is(TK::Variable))     { std::string v = tok.value; advance(); return {sparql::Term::Kind::Variable, v}; }
      if (is(TK::BlankNode))    { std::string v = tok.value; advance(); return {sparql::Term::Kind::BlankNode, v}; }
      if (kw("A")) { advance(); return {sparql::Term::Kind::Iri, "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"}; }
      throw std::runtime_error("Expected RDF term at line " + std::to_string(tok.line) + ", got '" + tok.value + "'");
   }

   std::vector<sparql::Triple> parseTriples(const std::map<std::string, std::string>& pref) {
      std::vector<sparql::Triple> out;
      while (!is(TK::RBrace) && !is(TK::Eof) && !kw("GRAPH") && !kw("OPTIONAL") &&
             !kw("FILTER")  && !kw("UNION")  && !kw("MINUS")  && !kw("SERVICE") &&
             !kw("BIND")    && !kw("VALUES")  && !is(TK::LBrace)) {
         if (is(TK::Dot)) { advance(); continue; }
         sparql::Term s = parseTerm(pref);
         sparql::Term p = parseTerm(pref);
         sparql::Term o = parseTerm(pref);
         out.push_back({s, p, o});
         // ';' shorthand: same subject, new predicate+object pairs
         while (is(TK::Semicolon)) {
            advance();
            if (is(TK::Dot) || is(TK::RBrace) || is(TK::Eof)) break;
            sparql::Term p2 = parseTerm(pref);
            sparql::Term o2 = parseTerm(pref);
            out.push_back({s, p2, o2});
         }
         // ',' shorthand: same subject+predicate, new objects
         while (is(TK::Comma)) {
            advance();
            out.push_back({s, p, parseTerm(pref)});
         }
         if (is(TK::Dot)) advance();
      }
      return out;
   }

   // Parses a `{ ... }` group into `out`. Recursive so it can also parse the
   // nested group of an OPTIONAL block — SPARQL allows GRAPH clauses, plain
   // triples, and (nested) OPTIONAL blocks inside an OPTIONAL just like at the
   // top level.
   void parseGroup(std::vector<std::unique_ptr<sparql::PatternElement>>& out,
                   const std::map<std::string, std::string>& prefixes,
                   const std::string& activeGraph) {
      eat(TK::LBrace);
      while (!is(TK::RBrace) && !is(TK::Eof)) {
         if (is(TK::Dot)) { advance(); continue; }

         if (kw("GRAPH")) {
            advance();
            std::string uri;
            if      (is(TK::IRI))          { uri = tok.value; advance(); }
            else if (is(TK::PrefixedName)) { uri = expandPrefix(tok.value, prefixes); advance(); }
            else throw std::runtime_error("Expected graph IRI after GRAPH at line " + std::to_string(tok.line));
            // Recurse with `uri` as the active graph so OPTIONAL, nested GRAPH,
            // and bare triples inside this block are all tagged with it —
            // mirrors how the top-level group is parsed.
            parseGroup(out, prefixes, uri);
            continue;
         }

         if (kw("OPTIONAL")) {
            advance();
            auto opt = std::make_unique<sparql::OptionalPattern>();
            parseGroup(opt->patterns, prefixes, activeGraph);
            out.push_back(std::move(opt));
            continue;
         }

         // Extension point: raise descriptive error for unsupported ARQ operators
         for (const char* op : {"FILTER","UNION","MINUS","SERVICE","BIND","VALUES"}) {
            if (kw(op)) throw std::runtime_error(std::string("ARQ operator '") + op + "' is not yet supported");
         }

         if (is(TK::LBrace)) {
            auto gp = std::make_unique<sparql::GraphPattern>();
            gp->graphUri = activeGraph;
            eat(TK::LBrace);
            gp->triples = parseTriples(prefixes);
            eat(TK::RBrace);
            if (!gp->triples.empty()) out.push_back(std::move(gp));
            continue;
         }

         auto triples = parseTriples(prefixes);
         if (!triples.empty()) {
            auto gp = std::make_unique<sparql::GraphPattern>();
            gp->graphUri = activeGraph;
            gp->triples = std::move(triples);
            out.push_back(std::move(gp));
         }
      }
      eat(TK::RBrace);
   }

   public:
   explicit Parser(std::string input) : tz(std::move(input)) { advance(); }

   sparql::Query parse() {
      sparql::Query q;

      // Prologue: PREFIX / BASE
      while (kw("PREFIX") || kw("BASE")) {
         if (kw("BASE")) { advance(); if (is(TK::IRI)) advance(); continue; }
         advance(); // consume PREFIX
         // Prefix label — tokenizer produces "ex:" as PrefixedName or ":" as Colon
         std::string label;
         if (is(TK::PrefixedName)) {
            // strip trailing ':'
            label = tok.value;
            auto c = label.rfind(':');
            if (c != std::string::npos) label = label.substr(0, c);
            advance();
         } else if (is(TK::Colon)) {
            label = ""; advance(); // default prefix
         } else if (is(TK::Keyword)) {
            label = tok.value; advance(); // keyword used as prefix name
            if (is(TK::Colon)) advance();
         }
         if (!is(TK::IRI))
            throw std::runtime_error("Expected IRI in PREFIX declaration at line " + std::to_string(tok.line));
         q.prefixes[label] = tok.value; advance();
      }

      // SELECT
      eatKw("SELECT");
      while (kw("DISTINCT") || kw("REDUCED")) advance();
      if (is(TK::Star)) { advance(); q.selectStar = true; }
      else {
         while (is(TK::Variable)) { q.selectVars.push_back(tok.value); advance(); }
         if (q.selectVars.empty())
            throw std::runtime_error("SELECT requires variables or * at line " + std::to_string(tok.line));
      }

      // Optional FROM clause (ignored — graph given via GRAPH clause)
      while (kw("FROM")) { advance(); if (kw("NAMED")) advance(); if (is(TK::IRI) || is(TK::PrefixedName)) advance(); }

      if (kw("WHERE")) advance();
      parseGroup(q.patterns, q.prefixes, "");

      while (!is(TK::Eof)) advance();
      return q;
   }
};

// ============================================================
// MLIR Translation
// ============================================================
namespace {
using namespace lingodb::compiler::dialect;
using namespace gengodb::compiler::dialect;

// Produce a short, MLIR-identifier-safe alias from a URI using the filename.
// file://resources/ttl/coffee.ttl#rdf -> "coffee"
static std::string uriAlias(const std::string& uri) {
   // Strip fragment
   std::string name = uri;
   auto hash = name.rfind('#');
   if (hash != std::string::npos) name = name.substr(0, hash);
   // Take last path segment
   auto slash = name.rfind('/');
   if (slash != std::string::npos) name = name.substr(slash + 1);
   // Strip file extension
   auto dot = name.rfind('.');
   if (dot != std::string::npos) name = name.substr(0, dot);
   if (name.empty()) name = "graph";
   // Sanitize to a valid MLIR identifier
   std::string r;
   for (char c : name)
      r += (std::isalnum(static_cast<unsigned char>(c)) || c == '_') ? c : '_';
   if (r.empty() || std::isdigit(static_cast<unsigned char>(r[0]))) r = "g_" + r;
   return r;
}

class Translator {
   mlir::MLIRContext* ctxt;
   mlir::OpBuilder& builder;
   tuples::ColumnManager& colMgr;
   subop::MemberManager& memMgr;

   // graph URI → (alias, named_graph output stream)
   std::map<std::string, std::pair<std::string, mlir::Value>> graphInfo;
   int graphCount{0};

   // Variable tracking — global across all BGPs.
   // First occurrence of a variable anywhere → ColumnDefAttr.
   // All subsequent occurrences → ColumnRefAttr.
   // Since later BGPs chain on the previous BGP's output stream, the column
   // is already present in the tuple stream when it appears as a ref.
   std::vector<std::string> allVars; // in order of first appearance
   std::map<std::string, tuples::ColumnDefAttr> varDefs;

   // Return (alias, named_graph stream) — creates NamedGraphOp on first use.
   std::pair<std::string, mlir::Value> namedGraph(const std::string& uri) {
      auto it = graphInfo.find(uri);
      if (it != graphInfo.end()) return it->second;

      std::string alias = uriAlias(uri);
      for (auto& [u, info] : graphInfo) {
         if (info.first == alias) { alias += "_" + std::to_string(graphCount); break; }
      }
      graphCount++;

      auto graphDef = colMgr.createDef("graphs", alias);
      graphDef.getColumn().type = gpm::GraphReferenceType::get(ctxt, mlir::StringAttr::get(ctxt, alias), mlir::StringAttr::get(ctxt, uri));
      auto loc = builder.getUnknownLoc();
      mlir::Value stream = builder.create<gpm::NamedGraphOp>(loc, graphDef);
      graphInfo[uri] = {alias, stream};
      return {alias, stream};
   }

   // Build a term attribute for TriplePatternOp.
   // Global variable tracking: first occurrence anywhere → ColumnDefAttr,
   // all subsequent occurrences (same or later BGP) → ColumnRefAttr.
   mlir::Attribute termAttr(const sparql::Term& term) {
      if (term.kind == sparql::Term::Kind::Iri)
         return gpm::IdentifierTermAttr::get(ctxt, mlir::StringAttr::get(ctxt, term.value));

      if (term.kind == sparql::Term::Kind::Variable) {
         auto it = varDefs.find(term.value);
         if (it == varDefs.end()) {
            auto def = colMgr.createDef("vars", term.value);
            def.getColumn().type = gpm::VariableBindingType::get(ctxt);
            varDefs[term.value] = def;
            allVars.push_back(term.value);
            return gpm::VariableTermAttr::get(ctxt, def);
         }
         return gpm::VariableTermAttr::get(ctxt, colMgr.createRef(it->second.getColumnPtr().get()));
      }

      if (term.kind == sparql::Term::Kind::BlankNode)
         return gpm::BNodeTermAttr::get(ctxt, mlir::StringAttr::get(ctxt, term.value));

      throw std::runtime_error("Unknown term kind");
   }

   // Build a BasicGraphPatternOp for the given graph pattern.
   mlir::Value buildBGP(const sparql::GraphPattern& gp, mlir::Value inputStream,
                        tuples::ColumnRefAttr graphRef) {
      auto loc = builder.getUnknownLoc();
      auto bgpOp = builder.create<gpm::BasicGraphPatternOp>(
         loc, tuples::TupleStreamType::get(ctxt), inputStream);

      auto* block = new mlir::Block;
      block->addArgument(tuples::TupleStreamType::get(ctxt), loc);
      bgpOp.getPattern().push_back(block);
      {
         mlir::OpBuilder::InsertionGuard guard(builder);
         builder.setInsertionPointToStart(block);
         mlir::Value cur = block->getArgument(0);
         for (const auto& triple : gp.triples) {
            auto s = termAttr(triple.s);
            auto p = termAttr(triple.p);
            auto o = termAttr(triple.o);
            cur = builder.create<gpm::TriplePatternOp>(
               loc, tuples::TupleStreamType::get(ctxt), cur, graphRef, s, p, o);
         }
         builder.create<tuples::ReturnOp>(loc, cur);
      }
      return bgpOp.getRes();
   }

   // Build an OptionalGraphPatternOp: the nested group is translated against
   // the block argument (the stream accumulated so far), left-outer-joining
   // its result onto `inputStream`. Variables first bound inside may end up
   // null if the optional group has no match — this is exactly what
   // gpm.optional_graph_pattern's lowering (outer join, null-matches-all)
   // implements.
   mlir::Value buildOptional(const sparql::OptionalPattern& opt, mlir::Value inputStream) {
      auto loc = builder.getUnknownLoc();
      auto optOp = builder.create<gpm::OptionalGraphPatternOp>(
         loc, tuples::TupleStreamType::get(ctxt), inputStream);

      auto* block = new mlir::Block;
      block->addArgument(tuples::TupleStreamType::get(ctxt), loc);
      optOp.getPattern().push_back(block);
      {
         mlir::OpBuilder::InsertionGuard guard(builder);
         builder.setInsertionPointToStart(block);
         mlir::Value result = buildPatternGroup(opt.patterns, block->getArgument(0));
         if (!result)
            throw std::runtime_error("OPTIONAL block contains no supported graph patterns");
         builder.create<tuples::ReturnOp>(loc, result);
      }
      return optOp.getRes();
   }

   // Chains a sequence of pattern elements, each joined onto the result of the
   // previous one: GraphPattern elements become (nested) BasicGraphPatternOps,
   // OptionalPattern elements become OptionalGraphPatternOps wrapping a
   // recursive call over their own nested group.
   // `externalInput` seeds the chain (used as the first element's input if it
   // is set); it must be set for nested groups (the enclosing block argument)
   // and is left null only for the outermost call, where the very first
   // element instead seeds itself from its own named graph.
   mlir::Value buildPatternGroup(const std::vector<std::unique_ptr<sparql::PatternElement>>& patterns,
                                 mlir::Value externalInput) {
      mlir::Value prevStream = externalInput;
      for (const auto& elemPtr : patterns) {
         if (elemPtr->kind() == sparql::PatternElement::Kind::Graph) {
            const auto& gp = static_cast<const sparql::GraphPattern&>(*elemPtr);
            if (gp.graphUri.empty())
               throw std::runtime_error("Triple patterns without an explicit GRAPH clause are not yet supported");

            auto [alias, graphStream] = namedGraph(gp.graphUri);
            auto graphRef = colMgr.createRef("graphs", alias);

            // First element takes the named_graph stream; subsequent take the previous result.
            mlir::Value input = prevStream ? prevStream : graphStream;
            prevStream = buildBGP(gp, input, graphRef);
         } else if (elemPtr->kind() == sparql::PatternElement::Kind::Optional) {
            const auto& opt = static_cast<const sparql::OptionalPattern&>(*elemPtr);
            if (!prevStream)
               throw std::runtime_error("OPTIONAL cannot be the first pattern in a query");
            prevStream = buildOptional(opt, prevStream);
         }
      }
      return prevStream;
   }

   // Recursively creates NamedGraphOps for every GRAPH clause referenced
   // anywhere in the pattern tree (including inside OPTIONAL blocks), while
   // the builder's insertion point is still the top-level execution-group
   // block. A GraphPatternOp/OptionalGraphPatternOp body may only contain
   // triple patterns, nested graph patterns, or the terminator (see
   // verifyGraphPatternBody) — NamedGraphOp is not allowed there, so any graph
   // first referenced deep inside an OPTIONAL must be pre-created here rather
   // than lazily when its first triple is built.
   void preRegisterGraphs(const std::vector<std::unique_ptr<sparql::PatternElement>>& patterns) {
      for (const auto& elemPtr : patterns) {
         if (elemPtr->kind() == sparql::PatternElement::Kind::Graph) {
            const auto& gp = static_cast<const sparql::GraphPattern&>(*elemPtr);
            if (!gp.graphUri.empty()) namedGraph(gp.graphUri);
         } else if (elemPtr->kind() == sparql::PatternElement::Kind::Optional) {
            const auto& opt = static_cast<const sparql::OptionalPattern&>(*elemPtr);
            preRegisterGraphs(opt.patterns);
         }
      }
   }

   public:
   Translator(mlir::MLIRContext* ctxt, mlir::OpBuilder& builder)
      : ctxt(ctxt), builder(builder),
        colMgr(ctxt->getLoadedDialect<tuples::TupleStreamDialect>()->getColumnManager()),
        memMgr(ctxt->getLoadedDialect<subop::SubOperatorDialect>()->getMemberManager()) {}

   void translate(const sparql::Query& query) {
      auto loc = builder.getUnknownLoc();

      // All GPM ops go inside a floating block that will become the query body.
      auto* egBlock = new mlir::Block;
      mlir::Type tableType;
      mlir::Value matResult;
      {
         mlir::OpBuilder::InsertionGuard guard(builder);
         builder.setInsertionPointToStart(egBlock);

         // Pre-create every referenced named graph up front (see preRegisterGraphs),
         // then chain the top-level pattern elements: each GraphPattern becomes a
         // BasicGraphPatternOp, each OptionalPattern an OptionalGraphPatternOp,
         // joined onto the result of the previous element. With global variable
         // tracking, variables bound earlier appear as ColumnRefAttrs later on —
         // valid because later elements receive the accumulated tuple stream.
         preRegisterGraphs(query.patterns);
         mlir::Value prevStream = buildPatternGroup(query.patterns, {});

         if (!prevStream)
            throw std::runtime_error("WHERE clause contains no supported graph patterns");

         // Project the requested variables
         std::vector<std::string> outVars = query.selectStar ? allVars : query.selectVars;

         llvm::SmallVector<subop::Member> members;
         llvm::SmallVector<mlir::Attribute> colRefs, colNames;
         for (size_t i = 0; i < outVars.size(); i++) {
            const auto& vn = outVars[i];
            if (std::find(allVars.begin(), allVars.end(), vn) == allVars.end())
               throw std::runtime_error("Selected variable ?" + vn + " is not bound in WHERE clause");
            members.push_back(memMgr.createMember("col" + std::to_string(i + 1), db::StringType::get(ctxt)));
            colRefs.push_back(colMgr.createRef("vars", vn));
            colNames.push_back(mlir::StringAttr::get(ctxt, vn));
         }

         tableType = subop::LocalTableType::get(
            ctxt,
            subop::StateMembersAttr::get(ctxt, members),
            mlir::ArrayAttr::get(ctxt, colNames));

         auto mat = builder.create<relalg::MaterializeOp>(
            loc, tableType, prevStream,
            mlir::ArrayAttr::get(ctxt, colRefs),
            mlir::ArrayAttr::get(ctxt, colNames));
         matResult = mat.getResult();

         builder.create<relalg::QueryReturnOp>(loc, mlir::ValueRange{matResult});
      }

      // Wrap the floating block in a query op
      auto execGroup = builder.create<relalg::QueryOp>(
         loc, mlir::TypeRange{tableType}, mlir::ValueRange{});
      execGroup.getRegion().push_back(egBlock);

      builder.create<subop::SetResultOp>(loc, 0, execGroup.getResults().front());
   }
};

// Register all dialects needed for SPARQL→MLIR translation and execution.
inline void registerSparqlDialects(mlir::MLIRContext& context) {
   mlir::DialectRegistry registry;
   registry.insert<mlir::BuiltinDialect,
                   relalg::RelAlgDialect,
                   subop::SubOperatorDialect,
                   tuples::TupleStreamDialect,
                   db::DBDialect,
                   mlir::func::FuncDialect,
                   mlir::arith::ArithDialect,
                   mlir::memref::MemRefDialect,
                   util::UtilDialect,
                   mlir::scf::SCFDialect,
                   mlir::LLVM::LLVMDialect,
                   gpm::GPMDialect>();
   context.appendDialectRegistry(registry);
   context.loadAllAvailableDialects();
}

// Translate a SPARQL query string to an MLIR module, printing it to `out`.
inline void translateSparqlToMLIR(const std::string& sparqlQuery, llvm::raw_ostream& out) {
   mlir::MLIRContext context;
   registerSparqlDialects(context);

   mlir::OpBuilder builder(&context);
   mlir::ModuleOp moduleOp = builder.create<mlir::ModuleOp>(builder.getUnknownLoc());
   builder.setInsertionPointToStart(moduleOp.getBody());

   auto* queryBlock = new mlir::Block;
   {
      mlir::OpBuilder::InsertionGuard guard(builder);
      builder.setInsertionPointToStart(queryBlock);

      Parser parser(sparqlQuery);
      sparql::Query query = parser.parse();

      Translator translator(&context, builder);
      translator.translate(query);

      builder.create<mlir::func::ReturnOp>(builder.getUnknownLoc());
   }

   mlir::func::FuncOp funcOp = builder.create<mlir::func::FuncOp>(
      builder.getUnknownLoc(), "main",
      builder.getFunctionType({}, {}));
   funcOp.getBody().push_back(queryBlock);

   mlir::OpPrintingFlags flags;
   flags.assumeVerified();
   moduleOp->print(out, flags);
   moduleOp.erase();
}

// Convenience overload: returns the MLIR module as a string.
inline std::string translateSparqlToMLIRString(const std::string& sparqlQuery) {
   std::string result;
   llvm::raw_string_ostream os(result);
   translateSparqlToMLIR(sparqlQuery, os);
   return result;
}

} // anonymous namespace

#endif // GENGODB_COMPILER_FRONTEND_SPARQLMLIPTRANSLATOR_H
/* --====-- (!) This file was generated by Claude Code (!) --====-- */
