/* --====-- (!) This file was generated by Claude Code (!) --====-- */
#include "features.h"
#include "lingodb/compiler/mlir-support/eval.h"
#include "lingodb/execution/Execution.h"
#include "lingodb/execution/Timing.h"
#include "lingodb/scheduler/Scheduler.h"
#include "lingodb/utility/Setting.h"

// SparqlMLIRTranslator includes MLIR dialect headers that introduce
// lingodb::compiler::dialect::arrow; include execution headers above first
// to avoid ambiguity with Apache Arrow's ::arrow namespace.
// #include "gengodb/compiler/frontend/SparqlMLIRTranslator.h"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

namespace {
lingodb::utility::GlobalSetting<bool> eagerLoading("system.eager_loading", false);
} // namespace

int main(int argc, char** argv) {
   using namespace lingodb;

   if (argc == 2 && std::string(argv[1]) == "--features") {
      printFeatures();
      return 0;
   }

   if (argc <= 2) {
      std::cerr << "USAGE: run-sparql *.sparql database" << std::endl;
      return 1;
   }

   std::string inputFileName = std::string(argv[1]);
   std::string directory = std::string(argv[2]);

   std::ifstream istream{inputFileName};
   if (!istream) {
      std::cerr << "Cannot open: " << inputFileName << std::endl;
      return 1;
   }
   std::stringstream buf;
   buf << istream.rdbuf();

   std::string mlirText;
   try {
      //mlirText = translateSparqlToMLIRString(buf.str());
   } catch (const std::exception& e) {
      std::cerr << "Error translating SPARQL: " << e.what() << std::endl;
      return 1;
   }

   std::cout << "Loading Database from: " << directory << '\n';
   auto session = runtime::Session::createSession(directory, eagerLoading.getValue());

   lingodb::compiler::support::eval::init();
   execution::ExecutionMode runMode = execution::getExecutionMode();
   auto queryExecutionConfig = execution::createQueryExecutionConfig(runMode, false);
   queryExecutionConfig->timingProcessor = std::make_unique<execution::TimingPrinter>(inputFileName);

   auto scheduler = scheduler::startScheduler();
   auto executer = execution::QueryExecuter::createDefaultExecuter(std::move(queryExecutionConfig), *session);
   executer->fromData(mlirText);
   scheduler::awaitEntryTask(std::make_unique<execution::QueryExecutionTask>(std::move(executer)));
   return 0;
}
/* --====-- (!) This file was generated by Claude Code (!) --====-- */
